### ISSUE TITLE
Check homework "WebApp"

### ISSUE THREAD

**Issue by KonAnd13** [KonAnd13/WebApp#1]

**Comment by KonAnd13** [comment]
Проблема со знаком '>' в поле Auto Name, не могу найти откуда он берется?

**Comment by coursar** [comment]
https://github.com/KonAnd13/WebApp/blob/bbc9ff9099474d1bc6fae7320c67b940033fca30/src/main/webapp/WEB-INF/catalog.jsp#L27

`<` перед `</h5>` нужно убрать, должен быть только один `<`.
